services:
  user-service:
    image: hwangrock/user-service:latest
    container_name: user-service
    ports:
      - "8081:8081"
    restart: always
    networks:
      - msa-network

  post-service:
    image: hwangrock/post-service:latest
    container_name: post-service
    ports:
      - "8082:8082"
    restart: always
    depends_on:
      - user-service
    networks:
      - msa-network

  notification-service:
    image: hwangrock/notification-service:latest
    container_name: notification-service
    ports:
      - "8083:8083"
    restart: always
    depends_on:
      - user-service
      - post-service
    networks:
      - msa-network


networks:
  msa-network:
    driver: bridge
