services:
  eureka-server:
    image: hwangrock/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - msa-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123  # 이 놈들은
      MYSQL_DATABASE: msa          # 나중에
      MYSQL_USER: hwangrock          # spring cloud config에
      MYSQL_PASSWORD: abc1234         # 보관해야함
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - msa-network

  user-service:
    image: hwangrock/user-service:latest
    container_name: user-service
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - eureka-server
      - mysql
    networks:
      - msa-network

  post-service:
    image: hwangrock/post-service:latest
    container_name: post-service
    ports:
      - "8082:8082"
    restart: always
    depends_on:
      - eureka-server
      - mysql
    networks:
      - msa-network

  notification-service:
    image: hwangrock/notification-service:latest
    container_name: notification-service
    ports:
      - "8083:8083"
    restart: always
    depends_on:
      - eureka-server
      - mysql
    networks:
      - msa-network

  api-gateway:
    image: hwangrock/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8084:8084"
    restart: always
    depends_on:
      - eureka-server
    networks:
      - msa-network
  
volumes:
  mysql_data:

networks:
  msa-network:
    driver: bridge
